#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CH_Hacker_Arms_AnimBP

#include "Basic.hpp"

#include "CH_Hacker_Arms_AnimBP_classes.hpp"
#include "CH_Hacker_Arms_AnimBP_parameters.hpp"


namespace SDK
{

// Function CH_Hacker_Arms_AnimBP.CH_Hacker_Arms_AnimBP_C.ExecuteUbergraph_CH_Hacker_Arms_AnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCH_Hacker_Arms_AnimBP_C::ExecuteUbergraph_CH_Hacker_Arms_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CH_Hacker_Arms_AnimBP_C", "ExecuteUbergraph_CH_Hacker_Arms_AnimBP");

	Params::CH_Hacker_Arms_AnimBP_C_ExecuteUbergraph_CH_Hacker_Arms_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CH_Hacker_Arms_AnimBP.CH_Hacker_Arms_AnimBP_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCH_Hacker_Arms_AnimBP_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CH_Hacker_Arms_AnimBP_C", "BlueprintUpdateAnimation");

	Params::CH_Hacker_Arms_AnimBP_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CH_Hacker_Arms_AnimBP.CH_Hacker_Arms_AnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UCH_Hacker_Arms_AnimBP_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CH_Hacker_Arms_AnimBP_C", "AnimGraph");

	Params::CH_Hacker_Arms_AnimBP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}

}

